"""add trophys DB

Revision ID: 515a9fc2ac18
Revises: bf170fc6a927
Create Date: 2024-11-25 17:05:47.186028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515a9fc2ac18'
down_revision: Union[str, None] = 'bf170fc6a927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trophys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fish', sa.String(length=255), nullable=False),
    sa.Column('base_weight', sa.String(length=50), nullable=False),
    sa.Column('rare_weight', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophys')
    # ### end Alembic commands ###
