"""fix

Revision ID: 96034ad30eee
Revises: 51d1728aa50d
Create Date: 2024-11-25 14:39:35.275128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96034ad30eee'
down_revision: Union[str, None] = '51d1728aa50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_id', sa.CHAR(length=36), nullable=False))
    op.drop_constraint('profiles_ibfk_1', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['user_id'])
    op.drop_column('profiles', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('user_uuid', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_ibfk_1', 'profiles', 'users', ['user_uuid'], ['user_id'])
    op.drop_column('profiles', 'user_id')
    # ### end Alembic commands ###
